---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstoredeployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: onlinebookstorelabel
  template:
    metadata:
      name: onlinebookstorepod
      labels:
        name: onlinebookstorelabel
    spec:
      containers:
        - name: onlinebookstoreapplication
          image: 851725269780.dkr.ecr.ap-south-1.amazonaws.com/onlinebookstoreimage:replaceImageTag
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebookstoresvc
spec:
  type: NodePort
  selector:
    name: onlinebookstorelabel
  ports:
    - port: 80
      targetPort: 8080
