---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstoredeployment
  namespace: d1cdffom
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onlinebookstorelabel
  template:
    metadata:
      name: onlinebookstorepod
      labels:
        name: onlinebookstorelabel
    spec:
      containers:
        - name: onlinebookstoreapplication
          image: srinivasulukokkinti/onlinebook:1
          ports:
            - containerPort: 8080
          resources:
            request:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: onlinebookstoresvc
  namespace: d1cdfom
spec:
  type: NodePort
  selector:
    name: onlinebookstorelabel
  ports:
    - port: 80
      targetPort: 8080
