name: SonarQube Test

on:
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build package
        run: mvn install -DskipTests
        cache:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          paths:
            - ~/.m2/repository      

      - name: Run SonarQube Analysis
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=onlinebookstore \
            -Dsonar.host.url=http://44.201.238.65:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}


      
        