name: sonar-queue-test

on:
  push:
    branches:
      - master

jobs:
  build_onlinebookstore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn install -DskipTests

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectKey: onlinebookstore
          sonarHostUrl: http://44.201.238.65:9000
          sonarToken: ${{ secrets.TOKEN }}
          args: >
            -Dsonar.java.binaries=target/classes

      - name: Check Quality Gate
        id: quality_gate_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          projectKey: onlinebookstore
          sonarHostUrl: http://44.201.238.65:9000
          sonarToken: ${{ secrets.TOKEN }}
          pollingTimeoutSec: 600

      - name: Print Quality Gate Result
        run: |
          if [ "${{ steps.quality_gate_check.outputs.quality_gate_status }}" = "PASSED" ]; then
            echo "✅ Quality gate passed successfully!"
          else
            echo "❌ Quality gate failed!"
          fi

      - name: Send email with result
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: srinivasulukokkinti1@gmail.com
          subject: "Githubaction pipeline result - ${{ steps.quality_gate_check.outputs.quality_gate_status }}"
          to: srinivasulukokkinti@gmail.com
          body: |
            Hello,

            The SonarQube Quality Gate has completed for the project **onlinebookstore**.

            Quality Gate Status: ${{ steps.quality_gate_check.outputs.quality_gate_status }}

            Regards,
            DevOps Pipeline
