name: onlinebookstore

on:
  workflow_dispatch:

jobs:
  onlinebookstore_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: sonar qulaiy check
        run:
           mvn sonar:sonar
          -Dsonar.projectKey=onlinebookstore
          -Dsonar.host.url=http://44.201.238.65:9000/
          -Dsonar.login=2f1c0e9d1b5f7e8d4c6a3f4b5a6b7c8d9e0f1g2h        
                      
                     