name: partose pipeline

on:
  push:
    branches:
      - master

jobs:
  gitleaksscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --config .gitleaks.toml --verbose --redact --exit-code 1

  build_onlinebookstore:
    needs: gitleaksscan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn install -DskipTests

      - name: Build and Push Docker image
        run: |
          docker build -t srinivasulukokkinti/onlinebookstore:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u srinivasulukokkinti --password-stdin
          docker push srinivasulukokkinti/onlinebookstore:latest
          docker logout

  kubernatesdeployjob:
    needs: build_onlinebookstore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubeconfig and deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl apply -f deployment/deployment-dev.yaml
