name: sonar-queue-test

on:
  push:
    branches:
      - master

jobs:
  build_onlinebookstore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn install -DskipTests

      - name: dockerimage 
        run: |
          docker build -t srinivasulukokkinti/onlinebookstore:latest -f onlinebookstore/WebContent/Dockerfile onlinebookstore/WebContent/
          docker login -u srinivasulukokkinti -p ${{ secrets.DOCKER_PASSWORD }}
          docker push srinivasulukokkinti/onlinebookstore:latest
          