name: sonar-queue-test

on:
  push:
    branches:
      - master

jobs:
  build_onlinebookstore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn install -DskipTests
      
      - name: Testing secerts
        env:
          DEVOPS: ${{ secrets.TOKEN }}
        run: echo "$DEVOPS" 
      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
         SONAR_TOKEN: ${{ secrets.TOKEN }}
        with:
         projectBaseDir: .
         args: >
          -Dsonar.projectName=onlinebookstore
          -Dsonar.host.url=http://44.201.238.65:9000

