name: outputworkflow

on:
  workflow_dispatch:

jobs:
  conditionalstatement:
    runs-on: ubuntu-latest
    steps:
      - name: print conditional statement
        if: github.ref_name == 'main'
        run: echo "running main branch"
